from typing import Any, Dict, List

__version__: str

def matching(zipcode: str) -> List[Dict[str, Any]]: ...
def is_real(zipcode: str) -> bool: ...
def similar_to(prefix: str) -> List[Dict[str, Any]]: ...
def contains(fragment: str) -> List[Dict[str, Any]]: ...
def filter_by(**filters: Any) -> List[Dict[str, Any]]: ...
def filter_by_coordinates(
    lat: float, long: float, radius_in_miles: float
) -> List[Dict[str, Any]]: ...
def haversine(lon1: float, lat1: float, lon2: float, lat2: float) -> float: ...
def list_all() -> List[Dict[str, Any]]: ...
