from typing import Any, Dict, List, Optional

__version__: str
FIELD_ORDER: List[str]

def matching(
    zipcode: str, zips: Optional[List[Dict[str, Any]]] = None
) -> List[Dict[str, Any]]: ...
def is_real(zipcode: str) -> bool: ...
def similar_to(
    prefix: str, zips: Optional[List[Dict[str, Any]]] = None
) -> List[Dict[str, Any]]: ...
def contains(
    fragment: str, zips: Optional[List[Dict[str, Any]]] = None
) -> List[Dict[str, Any]]: ...
def filter_by(
    zips: Optional[List[Dict[str, Any]]] = None, **filters: Any
) -> List[Dict[str, Any]]: ...
def filter_by_coordinates(
    lat: float,
    long: float,
    radius_in_miles: float,
    zips: Optional[List[Dict[str, Any]]] = None,
) -> List[Dict[str, Any]]: ...
def haversine(lon1: float, lat1: float, lon2: float, lat2: float) -> float: ...
def list_all() -> List[Dict[str, Any]]: ...
